function columnFunc(){
    let nameCheckbox = $('#nameCheckbox').prop('checked');
    let genderCheckbox = $('#genderCheckbox').prop('checked');
    let addressCheckbox = $('#addressCheckbox').prop('checked');
    let emailCheckbox = $('#emailCheckbox').prop('checked');
    let contactCheckbox = $('#contactCheckbox').prop('checked');
    let degreeCheckbox = $('#degreeCheckbox').prop('checked');
    let instituteCheckbox = $('#instituteCheckbox').prop('checked');
    let sessionCheckbox = $('#sessionCheckbox').prop('checked');
    let startCheckbox = $('#startCheckbox').prop('checked');
    let endCheckbox = $('#endCheckbox').prop('checked');
    let isLeftCheckbox = $('#isLeftCheckbox').prop('checked');
    let leftDateCheckbox = $('#leftDateCheckbox').prop('checked');
    let reasonCheckbox = $('#reasonCheckbox').prop('checked');
    let statusCheckbox = $('#statusCheckbox').prop('checked');

    let nameClass = (nameCheckbox == false) ? "d-print-none" : "";
    $("#nameTH").removeClass().addClass(nameClass);
    $(".nameTD").removeClass().addClass("nameTD "+nameClass);
    let genderClass = (genderCheckbox == false) ? "d-print-none" : "";
    $("#genderTH").removeClass().addClass(genderClass);
    $(".genderTD").removeClass().addClass("genderTD "+genderClass);
    let addressClass = (addressCheckbox == false) ? "d-print-none" : "";
    $("#addressTH").removeClass().addClass(addressClass);
    $(".addressTD").removeClass().addClass("addressTD "+addressClass);
    let emailClass = (emailCheckbox == false) ? "d-print-none" : "";
    $("#emailTH").removeClass().addClass(emailClass);
    $(".emailTD").removeClass().addClass("emailTD "+emailClass);
    let contactClass = (contactCheckbox == false) ? "d-print-none" : "";
    $("#contactTH").removeClass().addClass(contactClass);
    $(".contactTD").removeClass().addClass("contactTD "+contactClass);
    let degreeClass = (degreeCheckbox == false) ? "d-print-none" : "";
    $("#degreeTH").removeClass().addClass(degreeClass);
    $(".degreeTD").removeClass().addClass("degreeTD "+degreeClass);
    let instituteClass = (instituteCheckbox == false) ? "d-print-none" : "";
    $("#instituteTH").removeClass().addClass(instituteClass);
    $(".instituteTD").removeClass().addClass("instituteTD "+instituteClass);
    let sessionClass = (sessionCheckbox == false) ? "d-print-none" : "";
    $("#sessionTH").removeClass().addClass(sessionClass);
    $(".sessionTD").removeClass().addClass("sessionTD "+sessionClass);
    let startClass = (startCheckbox == false) ? "d-print-none" : "";
    $("#startTH").removeClass().addClass(startClass);
    $(".startTD").removeClass().addClass("startTD "+startClass);
    let endClass = (endCheckbox == false) ? "d-print-none" : "";
    $("#endTH").removeClass().addClass(endClass);
    $(".endTD").removeClass().addClass("endTD "+endClass);
    let isLeftClass = (isLeftCheckbox == false) ? "d-print-none" : "";
    $("#isLeftTH").removeClass().addClass(isLeftClass);
    $(".isLeftTD").removeClass().addClass("isLeftTD "+isLeftClass);
    let leftDateClass = (leftDateCheckbox == false) ? "d-print-none" : "";
    $("#leftDateTH").removeClass().addClass(leftDateClass);
    $(".leftDateTD").removeClass().addClass("leftDateTD "+leftDateClass);
    let reasonClass = (reasonCheckbox == false) ? "d-print-none" : "";
    $("#reasonTH").removeClass().addClass(reasonClass);
    $(".reasonTD").removeClass().addClass("reasonTD "+reasonClass);
    let statusClass = (statusCheckbox == false) ? "d-print-none" : "";
    $("#statusTH").removeClass().addClass(statusClass);
    $(".statusTD").removeClass().addClass("statusTD "+statusClass);
}